name: "upload/download"

on:
  workflow_dispatch:
  
jobs:
  Upload:
    strategy:
      matrix:
        size: [1,2,3,4]
  
    runs-on: [ubuntu-latest]
    steps:
      - name: Create temporary directory
        run: echo "UPLOAD_DIR=$(mktemp -d)" >> $GITHUB_ENV
        shell: bash

      - name: Make a ${{ matrix.size }}GB random binary file
        run: |
          size=$(expr ${{ matrix.size }} '*' 1000)
          dd if=/dev/urandom of=${UPLOAD_DIR}/my-file bs=1M count=${size}
          tar -cvf ${{ matrix.size }}.tar -C ${UPLOAD_DIR} .
        shell: bash
  
      # We have to upload a single tar as opposed to separate files to retain permissions.
      - name: Upload tar of artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          compression-level: 0
          name: ${{ matrix.size }}
          path: ${{ matrix.size }}.tar
          retention-days: 1

  Download:
    strategy:
      matrix:
        size: [1,2,3,4]
    
    runs-on: [ubuntu-latest]
    needs: [Upload]
    steps:

      - name: Download ${{ matrix.size }}
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.size }}
          path: artifacts/${{ matrix.size }}

      - name: Untar downloaded artifacts
        run: |
          tar -xf artifacts/${{ matrix.size }}/${{ matrix.size }}.tar -C artifacts/${{ matrix.size }}
