# Post-merge Build
name: Build

# Controls when the workflow will run.
on:
  workflow_dispatch:
  push:

jobs:

  Build:
    runs-on: [ubuntu-latest]

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: actions/runner-images
          token: ${{ github.token }}
          path: "repo"

      - name: Pull docker image
        run: |
          docker pull jgilli/4gb
          docker save -o repo/docker.tar docker.io/jgilli/4gb:latest
        shell: bash
    
      - name: Create tar 
        run: |
          ls repo
          tar -cvf artifact-to-upload.tar repo
        shell: bash
  
      # We have to upload a single tar as opposed to separate files to retain permissions and prevent rate limiting.
      - name: Upload zip of artifacts
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: test-zip-upload
          path: artifact-to-upload.zip
          retention-days: 1
